# -*- coding: utf-8 -*-
{
    'name': 'HKD Core',
    'version': '1.0',
    'category': 'Hidden',
    'summary': 'Module nền tảng cho hệ thống HKD',
    'description': 'Chứa menu gốc và các cấu hình dùng chung cho toàn bộ hệ thống HKD.',
    'author': 'HKD',
    'depends': [
        'base_setup',
        'account',
        'sale_management',
        'sale',
        'point_of_sale',
        'product',
        'mrp',
        'stock',
        'hkd_sales',
        'hkd_purchase',
        'hkd_mrp',
        'hkd_tax_policy',
        'hkd_dashboard',
        'hkd_statements',
    ],
    'data': [
        'security/security.xml',
        'views/products_views.xml',
        'views/res_user_views.xml',
        'views/stock_views.xml',
        'views/mrp_bom_views.xml',
        'views/purchase_order_views.xml',
        'views/account_move_views.xml',
        'views/res_partner_views.xml',
        'views/product_template_views.xml',
        'views/menus.xml',
        'data/product_uoms.xml',
        'data/product_category_data.xml',
        'data/ingredients_data.xml',
        'data/products_data.xml',
        'data/semi_products_data.xml',
        'data/settings.xml',
        
    ],
    'installable': True,
    'application': True, 
    'auto_install': False,
}